version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: larvel-app
    container_name: app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PASSWORD: root
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: larvel-nginx 
    container_name: webserver 
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app  

  db:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata:   
    driver: local 
